name: Deploy WyPIC Bot

on:
  push:
    branches:
      - main
    paths:
      - WyPIC.py   # workflow срабатывает только если изменился этот файл

concurrency:
  group: deploy-wypic
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check secrets
        run: |
          echo "HOST=${{ secrets.SERVER_HOST }}"
          echo "USER=${{ secrets.SERVER_USER }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait before deploy
        run: sleep 5  # небольшая задержка перед деплоем

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}       # IP сервера
          username: ${{ secrets.SERVER_USER }}   # root
          key: ${{ secrets.SERVER_SSH_KEY }}     # приватный SSH ключ
          script: |
            cd /root/WyPIC
            git fetch --all
            git reset --hard origin/main
            systemctl daemon-reload
            systemctl restart wypic
